### ISSUE TITLE
Backup path?

### ISSUE THREAD

**Issue by SntRkt** [angt/glorytun#47] opened 2019-10-17 22:03 UTC
I see paths can be added with a state of up, backup, and down. I added a path in the backup state, thinking it would only pass traffic when the path in the up state became degraded. This does not seem to be the case though... the backup path seems to act just like the up path. Is this by design? Is there a way to have a backup path that only passe traffic when the path(s) in the up state are degraded?

**Comment by angt** [comment] 2019-10-18 07:25
Hi,
The backup mode was supported in 0.0.x.
Since 0.1.x this option is no longer available due to many changes in the code.
I was waiting for an issue to work on it :)

**Comment by SntRkt** [comment] 2019-10-23 15:44
Awesome, thanks!

**Comment by sweroam-mibr** [comment] 2020-01-02 19:19
Great! :) waiting for the feature to come back! :) nice software! keep up the good work :)

**Comment by angt** [comment] 2020-01-02 19:29
I just commited the new backup code in mud -> https://github.com/angt/mud/commit/e56abf5eaaa90fd7a7b5d5019ce9fdc9871e10a1

**Comment by angt** [comment] 2020-01-02 19:39
This is an iperf3 with one 20mbit path and one 10mbit backup path.
Coming soon :)

```Connecting to host 10.166.100.2, port 5201
Reverse mode, remote host 10.166.100.2 is sending
[  5] local 10.166.100.1 port 39284 connected to 10.166.100.2 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  2.05 MBytes  17.2 Mbits/sec
[  5]   1.00-2.00   sec  2.06 MBytes  17.3 Mbits/sec
[  5]   2.00-3.00   sec  1.98 MBytes  16.6 Mbits/sec
[  5]   3.00-4.00   sec  1.98 MBytes  16.6 Mbits/sec
[  5]   4.00-5.00   sec  1.98 MBytes  16.6 Mbits/sec
[  5]   5.00-6.00   sec  1.98 MBytes  16.6 Mbits/sec
[  5]   6.00-7.00   sec  1.98 MBytes  16.6 Mbits/sec
[  5]   7.00-8.00   sec  1.98 MBytes  16.6 Mbits/sec
[  5]   8.00-9.00   sec  1.17 MBytes  9.78 Mbits/sec  <-- master down
[  5]   9.00-10.00  sec   614 KBytes  5.03 Mbits/sec
[  5]  10.00-11.00  sec  1013 KBytes  8.30 Mbits/sec
[  5]  11.00-12.00  sec  1013 KBytes  8.30 Mbits/sec
[  5]  12.00-13.00  sec  1013 KBytes  8.30 Mbits/sec
[  5]  13.00-14.00  sec  1012 KBytes  8.29 Mbits/sec
[  5]  14.00-15.00  sec  1014 KBytes  8.31 Mbits/sec
[  5]  15.00-16.00  sec  1013 KBytes  8.30 Mbits/sec
[  5]  16.00-17.00  sec  1013 KBytes  8.30 Mbits/sec
[  5]  17.00-18.00  sec  1012 KBytes  8.29 Mbits/sec
[  5]  18.00-19.00  sec  1.21 MBytes  10.1 Mbits/sec  <-- master up
[  5]  19.00-20.00  sec  1.98 MBytes  16.6 Mbits/sec
[  5]  20.00-21.00  sec  1.98 MBytes  16.6 Mbits/sec
[  5]  21.00-22.00  sec  1.98 MBytes  16.6 Mbits/sec
[  5]  22.00-23.00  sec  1.98 MBytes  16.6 Mbits/sec
[  5]  23.00-24.00  sec  1.98 MBytes  16.6 Mbits/sec
[  5]  24.00-25.00  sec  1.98 MBytes  16.6 Mbits/sec
[  5]  25.00-26.00  sec  1.98 MBytes  16.6 Mbits/sec
^C[  5]  26.00-26.50  sec  1012 KBytes  16.6 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-26.50  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-26.50  sec  41.7 MBytes  13.2 Mbits/sec                  receiver```

**Comment by sweroam-mibr** [comment] 2020-01-02 22:57
nice! is it possible to bind each server path to a interface? 
wan1 1.2.3.3
wan2 4.3.2.1

**Comment by angt** [comment] 2020-01-03 11:02
Not yet, see #44.

**Comment by angt** [comment] 2020-01-03 15:40
Merged in master, confirmed for the next release.

**Closed by angt** 2020-01-03 15:40 UTC
Labels: enhancement
