### ISSUE TITLE
MTU problems

### ISSUE THREAD

**Issue by uryupinsk** [angt/glorytun#34] opened 2019-05-18 08:47 UTC
Hi,

I'm using OpenMPTCProuter to aggregate 2 WAN connections which have a MTU of 1500 each.

When I use Glorytun TCP (default on OpenMPTCProuter), tunnel interfaces on both OpenMPTCProuter the VPS have an MTU of 1500, which is correct. Speeds are somewhat good on a site to site OpenVPN UDP with a friend that also have OpenMPTCProuter running.

When I use Glorytun UDP (OpenMPTCProuter uses the latest commit on the VPS and an OpenWRT version on the router), tunnel interfaces on both OpenMPTCProuter and the VPS have an MTU of 1378 (same thing on my friend's install). Speeds are horrible with the OpenVPN UDP tunnel, as it certainly has to fragment packets. I tried to set `link-mtu`, `tun-mtu` and `mssfix` parameters on OpenVPN, but the performance is not good anyway.

When I try to force the MTU on Glorytun UDP with the LuCI interface on OpenMPTCProuter, it does nothing.

When I try to force the MTU of the Glorytun server on the VPS:

```
# glorytun set mtu 1500
mtu set to 1500
# glorytun show
server gt-udp-tun0:
  pid:       3114
  bind:      0.0.0.0 port 65001
  mtu:       1378
  cipher:    aes256gcm
```

We can clearly see that it does nothing.

I don't see any reason why Glorytun UDP sets a MTU of 1378 on the interface, and it's too bad because it would be more efficient than Glorytun TCP.

**Comment by angt** [comment] 2019-05-18 09:38
Hi,
Where does 1378 come from?
The MTU overhead of glorytun is 50 bytes (28 for UDP + 22 for mud).
If your network is 1500 then you should have 1450 in `glorytun show` (1472 for each path in `gloryutn path`).

**Comment by uryupinsk** [comment] 2019-05-18 10:21
I don't know where it's coming from.
A friend of mine have the same install as mine and he also see 1378 on the tunnel interface.
I recall that some days ago, on a previous version of the OpenMPTCProuter VPS, the MTU was 1450 or 1472 and all was working correctly, but I didn't do any change and the VPS scripts don't modify any of the Glorytun settings or version.

**Comment by uryupinsk** [comment] 2019-05-18 20:24
See the issue I have created at the OpenMPTCProuter Github page, there are strange things going on...

Link: [https://github.com/Ysurac/openmptcprouter/issues/485](https://github.com/Ysurac/openmptcprouter/issues/485)

**Comment by angt** [comment] 2019-05-20 13:59
Closing as it seems to me that the problem is on openmptcprouter.

**Closed by angt** 2019-05-20 13:59 UTC
